spring.application.name=avito-ad-splitter

# Запускаем приложение на порту 8081, чтобы обойти зависший порт 8080
server.port=8081

# Database configuration will be automatically provided by spring-boot-docker-compose
# spring.datasource.url=jdbc:postgresql://localhost:5432/avito_db
# spring.datasource.username=avito
# spring.datasource.password=password
# spring.datasource.driver-class-name=org.postgresql.Driver

# Instruct Docker Compose to only start the 'db' service to avoid port 8080 conflicts
spring.docker.compose.services=db

# Liquibase
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

# Swagger OpenAPI properties
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
